repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check
        args: ["-C", "./src/backend"]
      - id: poetry-lock
        args: ["-C", "./src/backend"]

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
      - id: poetry-export
        args:
          [
            "-C",
            "./src/backend",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: "src/frontend/.*.json"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: pretty-format-json
        exclude: "src/frontend/.*.json"
        args: [--autofix]
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file=./src/backend/pyproject.toml"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
