name: LaTeX Build

on:
  push:
    branches: [main]
    paths:
      - "**.tex"
      - "**.bib"
  pull_request:
    branches: [main]
    paths:
      - "**.tex"
      - "**.bib"

jobs:
  build-latex:
    name: Build LaTeX PDFs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document(s)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdfs
          path: |
            **/*.pdf
